trigger:
- main

pool:
  name: 'COMP367-Windows'

variables:
  project: '**/MyWebApp.csproj' # Specify the path to your csproj file instead of sln
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
steps:
- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

